[program:sockeon-websocket]
process_name=%(program_name)s
command=php /var/www/laravel-sockeon/artisan sockeon:serve
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/laravel-sockeon/storage/logs/sockeon-websocket.log
stopwaitsecs=3600
